package iris;

import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class IRIS_LogIn extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    public IRIS_LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ExitButton = new javax.swing.JButton();
        MinimizeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Log_NameLabel = new javax.swing.JLabel();
        Log_PassLabel = new javax.swing.JLabel();
        Log_Name = new javax.swing.JTextField();
        Log_SubLabel = new javax.swing.JLabel();
        Log_TitleLabel = new javax.swing.JLabel();
        Log_EnterButton = new javax.swing.JButton();
        Log_Redirect = new javax.swing.JLabel();
        Log_Logo = new javax.swing.JLabel();
        Log_AuthorityLabel = new javax.swing.JLabel();
        Log_Auth = new javax.swing.JComboBox<>();
        Log_Pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ExitButton.setText("X");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        MinimizeButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        MinimizeButton.setText("_");
        MinimizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeButtonMouseClicked(evt);
            }
        });
        MinimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimizeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(407, Short.MAX_VALUE)
                .addComponent(MinimizeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(MinimizeButton))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(46, 56, 56));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Log_NameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Log_NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        Log_NameLabel.setText("Name:");

        Log_PassLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Log_PassLabel.setForeground(new java.awt.Color(255, 255, 255));
        Log_PassLabel.setText("Password:");

        Log_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Log_SubLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        Log_SubLabel.setForeground(new java.awt.Color(252, 226, 5));
        Log_SubLabel.setText("IBITS Rental & Inventory System");

        Log_TitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Log_TitleLabel.setForeground(new java.awt.Color(227, 227, 227));
        Log_TitleLabel.setText("IRIS");

        Log_EnterButton.setText("Log In");
        Log_EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_EnterButtonActionPerformed(evt);
            }
        });

        Log_Redirect.setForeground(new java.awt.Color(204, 204, 204));
        Log_Redirect.setText("Request Account Registration");
        Log_Redirect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_RedirectMouseClicked(evt);
            }
        });

        Log_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iris/pictures/100x100.png"))); // NOI18N

        Log_AuthorityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Log_AuthorityLabel.setForeground(new java.awt.Color(255, 255, 255));
        Log_AuthorityLabel.setText("Authority:");

        Log_Auth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Log_Auth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Officer", "Admin" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Log_EnterButton)
                    .addComponent(Log_Redirect)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Log_Logo)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Log_TitleLabel)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Log_NameLabel)
                                    .addComponent(Log_PassLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Log_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                    .addComponent(Log_Pass)))
                            .addComponent(Log_SubLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(Log_AuthorityLabel)
                                .addGap(18, 18, 18)
                                .addComponent(Log_Auth, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(Log_TitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Log_SubLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Log_NameLabel)
                            .addComponent(Log_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Log_Logo))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Log_PassLabel)
                    .addComponent(Log_Pass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Log_AuthorityLabel)
                    .addComponent(Log_Auth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Log_EnterButton)
                .addGap(5, 5, 5)
                .addComponent(Log_Redirect)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void MinimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimizeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MinimizeButtonActionPerformed

    private void Log_EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_EnterButtonActionPerformed
        String logname = Log_Name.getText();
        String logpass = String.valueOf(Log_Pass.getPassword());
        String logauth = Log_Auth.getSelectedItem().toString();

        if(logname.equals("")|logpass.equals(""))
                {
                        JOptionPane.showMessageDialog(rootPane, "Some Fields are Empty", "Error", 1);
                }else	{
                try
		{
			con = IRIS_Connection.getConnection();
			pst = con.prepareStatement("select * from login_admin where acc_name = ? and password = ?");
			pst.setString(1, logname);
                        pst.setString(2, logpass);
			rs = pst.executeQuery();
			if(rs.next())
			{
				String s1 = rs.getString("authority");
				if(logauth.equalsIgnoreCase("Admin") && s1.equalsIgnoreCase("admin"))
				{
					IRIS_AdminAccounts out = new IRIS_AdminAccounts(logname);
                                        out.setVisible(true);
                                        out.pack();
                                        out.setLocationRelativeTo(null);
                                        out.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                        this.dispose();
				}else if(logauth.equalsIgnoreCase("Officer") && s1.equalsIgnoreCase("admin"))
				{
                                    
					IRIS_Home out = new IRIS_Home(logname);
                                        out.setVisible(true);
                                        out.pack();
                                        out.setLocationRelativeTo(null);
                                        out.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                        this.dispose();
				}else if(logauth.equalsIgnoreCase("Officer") && s1.equalsIgnoreCase("officer"))
				{
                                    
					IRIS_Home out = new IRIS_Home(logname);
                                        out.setVisible(true);
                                        out.pack();
                                        out.setLocationRelativeTo(null);
                                        out.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                        this.dispose();
				}else if(logauth.equalsIgnoreCase("Admin") && s1.equalsIgnoreCase("officer"))
				{
					JOptionPane.showMessageDialog(null,"Officers must have\nAdmin Authorization to access\nAccounts Registration");
				}
			}else
			{
				JOptionPane.showMessageDialog(null,"Account does not exist");
			}
		}catch(Exception ex)
		{
			System.out.println(""+ex);
		}
	}
    }//GEN-LAST:event_Log_EnterButtonActionPerformed

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void MinimizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeButtonMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeButtonMouseClicked

    private void Log_RedirectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_RedirectMouseClicked
        IRIS_Request out = new IRIS_Request();
        out.setVisible(true);
        out.pack();
        out.setLocationRelativeTo(null);
        out.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_Log_RedirectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IRIS_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IRIS_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IRIS_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IRIS_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IRIS_LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JComboBox<String> Log_Auth;
    private javax.swing.JLabel Log_AuthorityLabel;
    private javax.swing.JButton Log_EnterButton;
    private javax.swing.JLabel Log_Logo;
    private javax.swing.JTextField Log_Name;
    private javax.swing.JLabel Log_NameLabel;
    private javax.swing.JPasswordField Log_Pass;
    private javax.swing.JLabel Log_PassLabel;
    private javax.swing.JLabel Log_Redirect;
    private javax.swing.JLabel Log_SubLabel;
    private javax.swing.JLabel Log_TitleLabel;
    private javax.swing.JButton MinimizeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
