/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iris;

import java.sql.Connection;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class IRIS_NewItem extends javax.swing.JFrame {
    DateFormat dateformat = new SimpleDateFormat("MM-dd-yyyy"); 
    Date date = new Date();
    String rdate = dateformat.format(date);
    SimpleDateFormat timeformat = new SimpleDateFormat("HH:mm:ss");
    String rtime = timeformat.format(date);
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    private void ItemList(){
        Connection con1;
        PreparedStatement pst1;
        ResultSet rs1;
        try{
        con1 = IRIS_Connection.getConnection();
        pst1 = con1.prepareStatement("select * from inventory_item");
        rs1 = pst1.executeQuery();
        
        while(rs1.next()){
            String items = rs1.getString("item_name");
            Inv_Name.addItem(items);
        }
        }catch(SQLException e)
            {}
    }
    
    public IRIS_NewItem() {
        initComponents();
        ItemList();
        this.setLocationRelativeTo(null);
    }
    
    public IRIS_NewItem(String logname)
    { 
        initComponents();
        ItemList();
        Officer_Name.setText(logname);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        Inv_Label = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        Inv_LIName = new javax.swing.JLabel();
        Inv_LIDesc = new javax.swing.JLabel();
        Inv_Scroll = new javax.swing.JScrollPane();
        Inv_Desc = new javax.swing.JTextArea();
        Inv_LIStatus = new javax.swing.JLabel();
        Inv_Status = new javax.swing.JComboBox<>();
        Inv_LISource = new javax.swing.JLabel();
        Inv_Source = new javax.swing.JComboBox<>();
        Add = new javax.swing.JButton();
        Inv_Av = new javax.swing.JComboBox<>();
        Inv_LTot2 = new javax.swing.JLabel();
        Inv_LOfficer = new javax.swing.JLabel();
        Officer_Name = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Inv_Name = new javax.swing.JComboBox<>();
        Inv_AddNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1136, 814));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("IRIS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("IBITS Rental & Inventory System");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("_");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raven\\Documents\\NetBeansProjects\\JAVA\\pictures\\50x50.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(46, 56, 56));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Inv_Label.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        Inv_Label.setForeground(new java.awt.Color(252, 226, 5));
        Inv_Label.setText("Inventory");

        Inv_LIName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inv_LIName.setForeground(new java.awt.Color(204, 204, 204));
        Inv_LIName.setText("Item Name:");

        Inv_LIDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inv_LIDesc.setForeground(new java.awt.Color(204, 204, 204));
        Inv_LIDesc.setText("Item Description:");

        Inv_Desc.setColumns(20);
        Inv_Desc.setRows(5);
        Inv_Scroll.setViewportView(Inv_Desc);

        Inv_LIStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inv_LIStatus.setForeground(new java.awt.Color(204, 204, 204));
        Inv_LIStatus.setText("Item Status:");

        Inv_Status.setEditable(true);
        Inv_Status.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Inv_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Good Condition", "Under Repair", "Damaged" }));
        Inv_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inv_StatusActionPerformed(evt);
            }
        });

        Inv_LISource.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inv_LISource.setForeground(new java.awt.Color(204, 204, 204));
        Inv_LISource.setText("Item Source:");

        Inv_Source.setEditable(true);
        Inv_Source.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Inv_Source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bought", "Donated" }));

        Add.setText("Confirm");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        Inv_Av.setEditable(true);
        Inv_Av.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Inv_Av.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In Stock", "Under Rent", "Unavailable" }));

        Inv_LTot2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inv_LTot2.setForeground(new java.awt.Color(204, 204, 204));
        Inv_LTot2.setText("Item Availability:");

        Inv_LOfficer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inv_LOfficer.setForeground(new java.awt.Color(204, 204, 204));
        Inv_LOfficer.setText("Officer in Charge:");

        Officer_Name.setEditable(false);
        Officer_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Officer_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Officer_NameActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Inv_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Inv_Name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TV" }));
        Inv_Name.setSelectedIndex(-1);

        Inv_AddNew.setText("Add New Item");
        Inv_AddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inv_AddNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Separator)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Inv_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Inv_LOfficer)
                                .addGap(38, 38, 38)
                                .addComponent(Officer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Inv_LIDesc)
                                    .addComponent(Inv_LIName))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Inv_Scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(Inv_Name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(108, 108, 108)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Inv_LTot2)
                                    .addComponent(Inv_LISource)
                                    .addComponent(Inv_LIStatus))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Inv_Source, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Inv_Status, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Inv_Av, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(Inv_AddNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Add)))
                .addGap(40, 40, 40))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Inv_Label)
                    .addComponent(Inv_LOfficer)
                    .addComponent(Officer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Inv_LIName)
                            .addComponent(Inv_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(Inv_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Inv_LIDesc))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Inv_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inv_LIStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Inv_Source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inv_LISource))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Inv_Av, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Inv_LTot2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add)
                    .addComponent(Back)
                    .addComponent(Clear)
                    .addComponent(Inv_AddNew))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2MouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
         try {                                                  
            String name = Inv_Name.getSelectedItem().toString();
            String desc = Inv_Desc.getText();
            String status = Inv_Status.getSelectedItem().toString();
            if("Damaged".equals(status)||"Under Repair".equals(status))
            {
                Inv_Av.setSelectedItem("Unavailable");
            }
            else if("Good Condition".equals(status))
            {
                Inv_Av.setSelectedItem("In Stock");
            }
            String source = Inv_Source.getSelectedItem().toString();
            String avail = Inv_Av.getSelectedItem().toString();
            
            String officer = Officer_Name.getText();
            
            java.util.Date dateStr = dateformat.parse(rdate);
            java.sql.Date dateDB = new java.sql.Date(dateStr.getTime());
            
            PreparedStatement ps;
            String query = "INSERT INTO `inventory` (`item_name`, `item_description`, `item_status`, `item_source`, `item_availability`, `item_officer`, `item_date`) VALUES (?,?,?,?,?,?,?)";
            
            try {
                ps = IRIS_Connection.getConnection().prepareStatement(query);
                
                ps.setString(1,name);
                ps.setString(2,desc);
                ps.setString(3,status);
                ps.setString(4,source);
                ps.setString(5,avail);
                ps.setString(6,officer);
                ps.setDate(7,dateDB);
                
                if(ps.executeUpdate() > 0)
                {
                   int dialogRes = JOptionPane.showConfirmDialog(null,"Add Another Item to Inventory?","Confirm",JOptionPane.YES_NO_OPTION);
                    if(dialogRes == JOptionPane.YES_OPTION)
                    {String logname = Officer_Name.getText();
                    IRIS_NewItem res = new IRIS_NewItem(logname);
                    res.setVisible(true);
                    res.pack();
                    res.setLocationRelativeTo(null);
                    res.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();}
                    
                    else{
                        String logname = Officer_Name.getText();
                        IRIS_Inventory res = new IRIS_Inventory(logname);
                        res.setVisible(true);
                        res.pack();
                        res.setLocationRelativeTo(null);
                        res.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                            
                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Failed");
                Logger.getLogger(IRIS_Inventory.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ParseException ex) {
            Logger.getLogger(IRIS_Inventory.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_AddActionPerformed

    private void Officer_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Officer_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Officer_NameActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        String logname = Officer_Name.getText();
        IRIS_Inventory inv = new IRIS_Inventory(logname);
        inv.setVisible(true);
        inv.pack();
        inv.setLocationRelativeTo(null);
        inv.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();   
    }//GEN-LAST:event_BackActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Inv_Name.setSelectedItem("TV");
        Inv_Desc.setText("");
        Inv_Status.setSelectedItem("Brand New");
        Inv_Source.setSelectedItem("Bought");
        Inv_Av.setSelectedItem("In Stock");
    }//GEN-LAST:event_ClearActionPerformed

    private void Inv_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inv_StatusActionPerformed
        String status = Inv_Status.getSelectedItem().toString();
            if("Damaged".equals(status)||"Under Repair".equals(status))
            {
                Inv_Av.setSelectedItem("Unavailable");
                Inv_Av.setEnabled(false);
            }
            if("Good Condition".equals(status))
            {
                Inv_Av.setEnabled(true);
            }
    }//GEN-LAST:event_Inv_StatusActionPerformed

    private void Inv_AddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inv_AddNewActionPerformed
        String logname = Officer_Name.getText();
        IRIS_NewItemList inv = new IRIS_NewItemList(logname);
        inv.setVisible(true);
        inv.pack();
        inv.setLocationRelativeTo(null);
        inv.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_Inv_AddNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IRIS_NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IRIS_NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IRIS_NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IRIS_NewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IRIS_NewItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Back;
    private javax.swing.JButton Clear;
    private javax.swing.JButton Inv_AddNew;
    private javax.swing.JComboBox<String> Inv_Av;
    private javax.swing.JTextArea Inv_Desc;
    private javax.swing.JLabel Inv_LIDesc;
    private javax.swing.JLabel Inv_LIName;
    private javax.swing.JLabel Inv_LISource;
    private javax.swing.JLabel Inv_LIStatus;
    private javax.swing.JLabel Inv_LOfficer;
    private javax.swing.JLabel Inv_LTot2;
    private javax.swing.JLabel Inv_Label;
    private javax.swing.JComboBox<String> Inv_Name;
    private javax.swing.JScrollPane Inv_Scroll;
    private javax.swing.JComboBox<String> Inv_Source;
    private javax.swing.JComboBox<String> Inv_Status;
    private javax.swing.JTextField Officer_Name;
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
