package iris;

import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import java.sql.Connection;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;

public class IRIS_AdminRequest extends javax.swing.JFrame{
    
    DateFormat dateformat = new SimpleDateFormat("MM-dd-yyyy"); 
    DateFormat dateformat2 = new SimpleDateFormat("yyyy-MM-dd");
    Date date = new Date();
    String rdate = dateformat.format(date);
    String comdate = dateformat2.format(date);
    SimpleDateFormat timeformat = new SimpleDateFormat("HH:mm:ss");
    String rtime = timeformat.format(date);
    String accname,yearsection, schoolyear,password,requestid;
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    private void table_update(){
        //update table
        int c;
        try{
        con = IRIS_Connection.getConnection();
        pst = con.prepareStatement("select * from request");
        rs = pst.executeQuery();
        ResultSetMetaData rss = rs.getMetaData();
        c = rss.getColumnCount();
        
        DefaultTableModel df = (DefaultTableModel)Rs_Table.getModel();
        df.setRowCount(0);
        
        while(rs.next())
        {
                Vector v2 = new Vector();
                for(int a=1; a<=c; a++)
                {       
                        v2.add(rs.getString("request_id"));
                        v2.add(rs.getString("acc_name"));
                        v2.add(rs.getString("yearsection"));
                        v2.add(rs.getString("schoolyear"));
                        v2.add(rs.getString("password"));
                }df.addRow(v2);
        }
        
        Rs_Table.setAutoCreateRowSorter(true);
        }catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Failed");
                Logger.getLogger(IRIS_AdminRequest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public IRIS_AdminRequest() {
        initComponents();
        table_update();
        Rs_Table.setAutoCreateRowSorter(true);
        this.setLocationRelativeTo(null);
    }
    IRIS_AdminRequest(String logname)
    {   initComponents();
        table_update();
        Accounts_Admin.setText(logname);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rs_label = new javax.swing.JLabel();
        Rs_Sep = new javax.swing.JSeparator();
        Rs_Scroll = new javax.swing.JScrollPane();
        Rs_Table = new javax.swing.JTable();
        Rs_SearchBar = new javax.swing.JTextField();
        Inv_LTot6 = new javax.swing.JLabel();
        Accounts_LAdmin = new javax.swing.JLabel();
        Accounts_Admin = new javax.swing.JTextField();
        Accounts_LDate = new javax.swing.JLabel();
        Accounts_Date = new javax.swing.JTextField();
        Reg_AuthorityLabel = new javax.swing.JLabel();
        Log_Authority = new javax.swing.JComboBox<>();
        Acc_Delete = new javax.swing.JButton();
        Acc_Accept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("IRIS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("IBITS Rental & Inventory System");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raven\\Documents\\NetBeansProjects\\JAVA\\pictures\\50x50.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)
                        .addComponent(jButton1)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(46, 56, 56));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rs_label.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        rs_label.setForeground(new java.awt.Color(252, 226, 5));
        rs_label.setText("Account Requests");
        rs_label.setToolTipText("");

        Rs_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Year&Section", "School Year", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Rs_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Rs_TableMouseClicked(evt);
            }
        });
        Rs_Scroll.setViewportView(Rs_Table);
        if (Rs_Table.getColumnModel().getColumnCount() > 0) {
            Rs_Table.getColumnModel().getColumn(0).setResizable(false);
            Rs_Table.getColumnModel().getColumn(0).setPreferredWidth(30);
            Rs_Table.getColumnModel().getColumn(1).setResizable(false);
            Rs_Table.getColumnModel().getColumn(2).setResizable(false);
            Rs_Table.getColumnModel().getColumn(3).setResizable(false);
            Rs_Table.getColumnModel().getColumn(4).setResizable(false);
        }

        Rs_SearchBar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rs_SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rs_SearchBarActionPerformed(evt);
            }
        });
        Rs_SearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Rs_SearchBarKeyReleased(evt);
            }
        });

        Inv_LTot6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Inv_LTot6.setForeground(new java.awt.Color(204, 204, 204));
        Inv_LTot6.setText("Search:");

        Accounts_LAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Accounts_LAdmin.setForeground(new java.awt.Color(255, 255, 255));
        Accounts_LAdmin.setText("Current Admin:");

        Accounts_Admin.setEditable(false);
        Accounts_Admin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Accounts_Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accounts_AdminActionPerformed(evt);
            }
        });

        Accounts_LDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Accounts_LDate.setForeground(new java.awt.Color(255, 255, 255));
        Accounts_LDate.setText("Current Date:");

        Accounts_Date.setEditable(false);
        Accounts_Date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Accounts_Date.setText(rdate);
        Accounts_Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Accounts_DateActionPerformed(evt);
            }
        });

        Reg_AuthorityLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Reg_AuthorityLabel.setForeground(new java.awt.Color(255, 255, 255));
        Reg_AuthorityLabel.setText("Authority:");

        Log_Authority.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Log_Authority.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Officer", "Admin" }));

        Acc_Delete.setText("Deny");
        Acc_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acc_DeleteActionPerformed(evt);
            }
        });

        Acc_Accept.setText("Accept");
        Acc_Accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Acc_AcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Rs_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Accounts_LAdmin)
                            .addComponent(Accounts_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Accounts_LDate)
                            .addComponent(Accounts_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reg_AuthorityLabel)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(Acc_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Acc_Accept, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Log_Authority, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rs_label, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Inv_LTot6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Rs_SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addComponent(Rs_Sep)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rs_label)
                    .addComponent(Rs_SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inv_LTot6))
                .addGap(15, 15, 15)
                .addComponent(Rs_Sep, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Rs_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Accounts_LAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Accounts_Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Accounts_LDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Accounts_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Reg_AuthorityLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Log_Authority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Acc_Delete)
                            .addComponent(Acc_Accept))
                        .addGap(41, 41, 41))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String logname = Accounts_Admin.getText();
        IRIS_AdminAccounts rf = new IRIS_AdminAccounts(logname);
        rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(null);
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Rs_SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rs_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rs_SearchBarActionPerformed

    private void Rs_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Rs_TableMouseClicked
        DefaultTableModel df = (DefaultTableModel)Rs_Table.getModel();
        int selectedIndex = Rs_Table.getSelectedRow();
        
        requestid = (df.getValueAt(selectedIndex, 0).toString());
        accname = (df.getValueAt(selectedIndex, 1).toString());
        yearsection = (df.getValueAt(selectedIndex, 2).toString());
        schoolyear = (df.getValueAt(selectedIndex, 3).toString());
        password = (df.getValueAt(selectedIndex, 4).toString());

    }//GEN-LAST:event_Rs_TableMouseClicked

    private void Rs_SearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Rs_SearchBarKeyReleased
        DefaultTableModel df = (DefaultTableModel)Rs_Table.getModel();
        String search = Rs_SearchBar.getText().trim();
        
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(df);
        Rs_Table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_Rs_SearchBarKeyReleased

    private void Accounts_AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accounts_AdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Accounts_AdminActionPerformed

    private void Accounts_DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Accounts_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Accounts_DateActionPerformed

    private void Acc_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acc_DeleteActionPerformed
        try {
                    int rid = Integer.parseInt(requestid);
                    
                    PreparedStatement psd;
                    String del = "delete from request where request_id = ?";
                    psd = IRIS_Connection.getConnection().prepareStatement(del);
                    psd.setInt(1,rid);
                    psd.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Account Request Deleted.");
                    table_update();
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Failed");
                Logger.getLogger(IRIS_AdminRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_Acc_DeleteActionPerformed

    private void Acc_AcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Acc_AcceptActionPerformed
        try {
            int rid = Integer.parseInt(requestid);
            
            java.util.Date dateStr = dateformat.parse(rdate);
            java.sql.Date dateDB = new java.sql.Date(dateStr.getTime());
            
            String authtype = Log_Authority.getSelectedItem().toString();
            String admin = Accounts_Admin.getText();
            
            PreparedStatement ps, psd;
            String query = "INSERT INTO `login_admin`(`acc_name`, `yearsection`, `schoolyear`, `password`, `authority`, `reg_admin`, `reg_date`) VALUES (?,?,?,?,?,?,?)";
            
            try {
                ps = IRIS_Connection.getConnection().prepareStatement(query);
                
                ps.setString(1,accname);
                ps.setString(2,yearsection);
                ps.setString(3,schoolyear);
                ps.setString(4,password);
                ps.setString(5,authtype);
                ps.setString(6,admin);
                ps.setDate(7,dateDB);
                
                
                if(ps.executeUpdate() > 0)
                {   String del = "delete from request where request_id = ?";
                    psd = IRIS_Connection.getConnection().prepareStatement(del);
                    psd.setInt(1,rid);
                    psd.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Account Request Accepted.");
                    table_update();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Failed");
                Logger.getLogger(IRIS_AdminRegistration.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ParseException ex) {
            Logger.getLogger(IRIS_AdminRegistration.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_Acc_AcceptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IRIS_AdminRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IRIS_AdminRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IRIS_AdminRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IRIS_AdminRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IRIS_AdminRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acc_Accept;
    private javax.swing.JButton Acc_Delete;
    private javax.swing.JTextField Accounts_Admin;
    private javax.swing.JTextField Accounts_Date;
    private javax.swing.JLabel Accounts_LAdmin;
    private javax.swing.JLabel Accounts_LDate;
    private javax.swing.JLabel Inv_LTot6;
    private javax.swing.JComboBox<String> Log_Authority;
    private javax.swing.JLabel Reg_AuthorityLabel;
    private javax.swing.JScrollPane Rs_Scroll;
    private javax.swing.JTextField Rs_SearchBar;
    private javax.swing.JSeparator Rs_Sep;
    private javax.swing.JTable Rs_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel rs_label;
    // End of variables declaration//GEN-END:variables

}
