/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iris;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class IRIS_About extends javax.swing.JFrame {
    DateFormat dateformat = new SimpleDateFormat("MM-dd-yyyy"); 
    Date date = new Date();
    String rdate = dateformat.format(date);
    SimpleDateFormat timeformat = new SimpleDateFormat("HH:mm");
    String rtime = timeformat.format(date);
    int itemid = 0;
    String officer;
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public IRIS_About() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public IRIS_About(String logname)
    { 
        initComponents();
        officer = logname;
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        Rent_LDetails = new javax.swing.JLabel();
        Rent_LItemName1 = new javax.swing.JLabel();
        Rent_LDetails1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Rent_LDetails2 = new javax.swing.JLabel();
        Rent_LDetails3 = new javax.swing.JLabel();
        Rent_LItemName3 = new javax.swing.JLabel();
        Rent_LDetails4 = new javax.swing.JLabel();
        Rent_LDetails5 = new javax.swing.JLabel();
        Rent_LDetails6 = new javax.swing.JLabel();
        Rent_LDetails7 = new javax.swing.JLabel();
        Rent_LDetails8 = new javax.swing.JLabel();
        Rent_LItemName4 = new javax.swing.JLabel();
        Rent_LDetails9 = new javax.swing.JLabel();
        Rent_LDetails10 = new javax.swing.JLabel();
        Rent_LDetails11 = new javax.swing.JLabel();
        Rent_LDetails12 = new javax.swing.JLabel();
        Rent_LDetails13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1136, 814));

        jPanel3.setBackground(java.awt.SystemColor.textHighlight);
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raven\\Documents\\NetBeansProjects\\JAVA\\pictures\\100x100.png")); // NOI18N

        Rent_LDetails.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        Rent_LDetails.setForeground(new java.awt.Color(252, 226, 5));
        Rent_LDetails.setText("Java System and Project for OOP and HCI");

        Rent_LItemName1.setBackground(new java.awt.Color(255, 255, 255));
        Rent_LItemName1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Rent_LItemName1.setForeground(new java.awt.Color(255, 255, 255));
        Rent_LItemName1.setText("Languages");

        Rent_LDetails1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        Rent_LDetails1.setForeground(new java.awt.Color(252, 226, 5));
        Rent_LDetails1.setText("programming languages");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("IRIS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IBITS Rental & Inventory System");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Rent_LDetails2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Rent_LDetails2.setForeground(new java.awt.Color(51, 51, 51));
        Rent_LDetails2.setText("1. Java");

        Rent_LDetails3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Rent_LDetails3.setForeground(new java.awt.Color(51, 51, 51));
        Rent_LDetails3.setText("2. SQL");

        Rent_LItemName3.setBackground(new java.awt.Color(255, 255, 255));
        Rent_LItemName3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Rent_LItemName3.setForeground(new java.awt.Color(255, 255, 255));
        Rent_LItemName3.setText("Development");

        Rent_LDetails4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        Rent_LDetails4.setForeground(new java.awt.Color(252, 226, 5));
        Rent_LDetails4.setText("sources, packages, applications");

        Rent_LDetails5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Rent_LDetails5.setForeground(new java.awt.Color(51, 51, 51));
        Rent_LDetails5.setText("1. Netbeans");

        Rent_LDetails6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Rent_LDetails6.setForeground(new java.awt.Color(51, 51, 51));
        Rent_LDetails6.setText("2. XAMPP");

        Rent_LDetails7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Rent_LDetails7.setForeground(new java.awt.Color(51, 51, 51));
        Rent_LDetails7.setText("3. mysql connector java 5.1.46");

        Rent_LDetails8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Rent_LDetails8.setForeground(new java.awt.Color(51, 51, 51));
        Rent_LDetails8.setText("4. JCalendar 1.4");

        Rent_LItemName4.setBackground(new java.awt.Color(255, 255, 255));
        Rent_LItemName4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Rent_LItemName4.setForeground(new java.awt.Color(255, 255, 255));
        Rent_LItemName4.setText("Developers");

        Rent_LDetails9.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        Rent_LDetails9.setForeground(new java.awt.Color(252, 226, 5));
        Rent_LDetails9.setText("behind the system");

        Rent_LDetails10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Rent_LDetails10.setForeground(new java.awt.Color(51, 51, 51));
        Rent_LDetails10.setText("1. Avila, Zyrah Kae M.");

        Rent_LDetails11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Rent_LDetails11.setForeground(new java.awt.Color(51, 51, 51));
        Rent_LDetails11.setText("2. Nicolas, Raven");

        Rent_LDetails12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Rent_LDetails12.setForeground(new java.awt.Color(51, 51, 51));
        Rent_LDetails12.setText("3. Veneracion, Marielle");

        Rent_LDetails13.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        Rent_LDetails13.setForeground(new java.awt.Color(252, 226, 5));
        Rent_LDetails13.setText("BSIT 2-1N 2019-2020 PUPMNL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Rent_LDetails12)
                            .addComponent(Rent_LDetails10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rent_LDetails11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rent_LDetails1)
                            .addComponent(Rent_LItemName1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rent_LDetails2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Rent_LDetails3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Rent_LDetails9)
                            .addComponent(Rent_LItemName4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rent_LDetails4)
                            .addComponent(Rent_LItemName3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Rent_LDetails13)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Rent_LDetails5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Rent_LDetails6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Rent_LDetails7)
                                        .addComponent(Rent_LDetails8)))))
                        .addGap(39, 39, 39))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(190, 190, 190)
                        .addComponent(jButton1))
                    .addComponent(Rent_LDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(Rent_LDetails))
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Rent_LItemName3)
                        .addGap(1, 1, 1)
                        .addComponent(Rent_LDetails4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rent_LDetails5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rent_LDetails6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Rent_LItemName1)
                        .addGap(1, 1, 1)
                        .addComponent(Rent_LDetails1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rent_LDetails2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rent_LDetails3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Rent_LDetails7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rent_LDetails8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Rent_LItemName4)
                        .addGap(1, 1, 1)
                        .addComponent(Rent_LDetails9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rent_LDetails10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Rent_LDetails11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rent_LDetails12)
                            .addComponent(Rent_LDetails13))))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IRIS_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IRIS_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IRIS_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IRIS_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IRIS_About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Rent_LDetails;
    private javax.swing.JLabel Rent_LDetails1;
    private javax.swing.JLabel Rent_LDetails10;
    private javax.swing.JLabel Rent_LDetails11;
    private javax.swing.JLabel Rent_LDetails12;
    private javax.swing.JLabel Rent_LDetails13;
    private javax.swing.JLabel Rent_LDetails2;
    private javax.swing.JLabel Rent_LDetails3;
    private javax.swing.JLabel Rent_LDetails4;
    private javax.swing.JLabel Rent_LDetails5;
    private javax.swing.JLabel Rent_LDetails6;
    private javax.swing.JLabel Rent_LDetails7;
    private javax.swing.JLabel Rent_LDetails8;
    private javax.swing.JLabel Rent_LDetails9;
    private javax.swing.JLabel Rent_LItemName1;
    private javax.swing.JLabel Rent_LItemName3;
    private javax.swing.JLabel Rent_LItemName4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
