/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trash;

import com.mysql.jdbc.Statement;
import iris.IRIS_Connection;
import iris.IRIS_Inventory;
import iris.IRIS_LogIn;
import iris.IRIS_RentalForm;
import iris.IRIS_RentalSchedule;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class IRIS_ReservationForm extends javax.swing.JFrame {
DateFormat dateformat = new SimpleDateFormat("MM-dd-yyyy"); 
    Date date = new Date();
    String rdate = dateformat.format(date);
    SimpleDateFormat timeformat = new SimpleDateFormat("HH:mm");
    String rtime = timeformat.format(date);
    int itemid = 0;
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    public class Available{
       Connection con = null;
       ResultSet rs = null;
       PreparedStatement ps = null;
       public ResultSet find(String s){
           try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/irisdbms","root","");
           ps = con.prepareStatement("select item_description,item_id from inventory where item_name = ? and item_availability in ('In Stock')");
           ps.setString(1,s);
           rs = ps.executeQuery();
           }catch(Exception ex){
              JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs;
       }
   }
    public IRIS_ReservationForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public IRIS_ReservationForm(String logname)
    { 
        initComponents();
        Logged_Name.setText(logname);
        Officer_Name.setText(logname);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        inv_direct = new javax.swing.JButton();
        out_direct = new javax.swing.JButton();
        rs_direct = new javax.swing.JButton();
        tr_direct = new javax.swing.JButton();
        rf_direct = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Logged_Name = new javax.swing.JLabel();
        logged_as = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RentLabel = new javax.swing.JLabel();
        Rent_Ldate = new javax.swing.JLabel();
        Rent_CurrDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Officer_Name = new javax.swing.JTextField();
        Rent_LStuNo = new javax.swing.JLabel();
        Rent_StuNo = new javax.swing.JTextField();
        Rent_LStuName = new javax.swing.JLabel();
        Rent_StuName = new javax.swing.JTextField();
        Rent_LSection = new javax.swing.JLabel();
        Rent_Sect = new javax.swing.JTextField();
        Rent_LDetails = new javax.swing.JLabel();
        Rent_LDTR = new javax.swing.JLabel();
        Rent_DateChooser = new com.toedter.calendar.JDateChooser();
        Rent_LRoom = new javax.swing.JLabel();
        Rent_Room = new javax.swing.JTextField();
        Rent_LTin = new javax.swing.JLabel();
        Rent_LTout = new javax.swing.JLabel();
        Rent_LItemName = new javax.swing.JLabel();
        Rent_Name = new javax.swing.JComboBox<>();
        Rent_LItemDesc = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Rent_Confirm = new javax.swing.JButton();
        Rent_Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rent_ItemDesc = new javax.swing.JTextArea();
        Rent_LFee = new javax.swing.JLabel();
        Rent_Fee = new javax.swing.JTextField();
        Rent_Tin = new javax.swing.JSpinner();
        Rent_Tout = new javax.swing.JSpinner();
        Rent_LFee1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1136, 814));

        jPanel2.setBackground(new java.awt.Color(252, 226, 5));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        inv_direct.setText("Inventory");
        inv_direct.setPreferredSize(new java.awt.Dimension(155, 23));
        inv_direct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inv_directMouseClicked(evt);
            }
        });
        inv_direct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inv_directActionPerformed(evt);
            }
        });

        out_direct.setText("Log Out");
        out_direct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                out_directMouseClicked(evt);
            }
        });
        out_direct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                out_directActionPerformed(evt);
            }
        });

        rs_direct.setText("Transaction Records");
        rs_direct.setPreferredSize(new java.awt.Dimension(155, 23));
        rs_direct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs_directActionPerformed(evt);
            }
        });

        tr_direct.setText("Reservation Form");
        tr_direct.setPreferredSize(new java.awt.Dimension(155, 23));
        tr_direct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tr_directMouseClicked(evt);
            }
        });

        rf_direct.setText("Rental Form");
        rf_direct.setPreferredSize(new java.awt.Dimension(155, 23));
        rf_direct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rf_directMouseClicked(evt);
            }
        });
        rf_direct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rf_directActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raven\\Documents\\NetBeansProjects\\JAVA\\pictures\\100x100.png")); // NOI18N

        Logged_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        logged_as.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logged_as.setText("Signed in as:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inv_direct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rs_direct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tr_direct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rf_direct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(out_direct, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logged_as, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Logged_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rf_direct, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tr_direct, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(rs_direct, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inv_direct, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logged_as, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(Logged_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(out_direct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("IRIS");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("IBITS Rental & Inventory System");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("X");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("_");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Raven\\Documents\\NetBeansProjects\\JAVA\\pictures\\50x50.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(751, 751, 751))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(46, 56, 56));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        RentLabel.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        RentLabel.setForeground(new java.awt.Color(252, 226, 5));
        RentLabel.setText("Reservation Form");

        Rent_Ldate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_Ldate.setForeground(new java.awt.Color(204, 204, 204));
        Rent_Ldate.setText("Reservation Date:");

        Rent_CurrDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rent_CurrDate.setText(rdate);
        Rent_CurrDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rent_CurrDateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Officer in Charge:");

        Officer_Name.setEditable(false);
        Officer_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Rent_LStuNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LStuNo.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LStuNo.setText("Student Number:");

        Rent_StuNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rent_StuNo.setToolTipText("");
        Rent_StuNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rent_StuNoActionPerformed(evt);
            }
        });

        Rent_LStuName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LStuName.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LStuName.setText("Student Name:");

        Rent_StuName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rent_StuName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rent_StuNameActionPerformed(evt);
            }
        });

        Rent_LSection.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LSection.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LSection.setText("Section:");

        Rent_Sect.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Rent_LDetails.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        Rent_LDetails.setForeground(new java.awt.Color(252, 226, 5));
        Rent_LDetails.setText("Reservation Details");

        Rent_LDTR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LDTR.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LDTR.setText("Date to Rent:");

        Rent_DateChooser.setMinSelectableDate(date);

        Rent_LRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LRoom.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LRoom.setText("Room:");

        Rent_Room.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rent_Room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rent_RoomActionPerformed(evt);
            }
        });

        Rent_LTin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LTin.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LTin.setText("Time in:");

        Rent_LTout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LTout.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LTout.setText("Time Out:");

        Rent_LItemName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LItemName.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LItemName.setText("Item Name:");

        Rent_Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rent_Name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TV", "Extension", "HDMI", "VGA", "Damath", "Equalizer", "Chess", "Scrabble", "Game of the Generals" }));
        Rent_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rent_NameActionPerformed(evt);
            }
        });

        Rent_LItemDesc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LItemDesc.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LItemDesc.setText("Item Description:");

        Rent_Confirm.setText("Confirm");
        Rent_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rent_ConfirmActionPerformed(evt);
            }
        });

        Rent_Clear.setText("Clear");
        Rent_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rent_ClearActionPerformed(evt);
            }
        });

        Rent_ItemDesc.setEditable(false);
        Rent_ItemDesc.setColumns(20);
        Rent_ItemDesc.setRows(5);
        jScrollPane1.setViewportView(Rent_ItemDesc);

        Rent_LFee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LFee.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LFee.setText("Fee:");

        Rent_Fee.setEditable(false);
        Rent_Fee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Rent_Tin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rent_Tin.setModel(new javax.swing.SpinnerListModel(new String[] {"07:00", "07:15", "07:30", "07:45", "08:00", "08:15", "08:30", "08:45", "09:00", "09:15", "09:30", "09:45", "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:30", "11:45", "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30", "21:45", "22:00", "22:15", "22:30"}));

        Rent_Tout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rent_Tout.setModel(new javax.swing.SpinnerListModel(new String[] {"07:00", "07:15", "07:30", "07:45", "08:00", "08:15", "08:30", "08:45", "09:00", "09:15", "09:30", "09:45", "10:00", "10:15", "10:30", "10:45", "11:00", "11:15", "11:30", "11:45", "12:00", "12:15", "12:30", "12:45", "13:00", "13:15", "13:30", "13:45", "14:00", "14:15", "14:30", "14:45", "15:00", "15:15", "15:30", "15:45", "16:00", "16:15", "16:30", "16:45", "17:00", "17:15", "17:30", "17:45", "18:00", "18:15", "18:30", "18:45", "19:00", "19:15", "19:30", "19:45", "20:00", "20:15", "20:30", "20:45", "21:00", "21:15", "21:30", "21:45", "22:00", "22:15", "22:30"}));

        Rent_LFee1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Rent_LFee1.setForeground(new java.awt.Color(204, 204, 204));
        Rent_LFee1.setText("₱");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(Rent_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Rent_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Rent_LRoom)
                                            .addComponent(Rent_LTin)
                                            .addComponent(Rent_LTout)
                                            .addComponent(Rent_LDTR))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Rent_Room)
                                                .addComponent(Rent_Tin)
                                                .addComponent(Rent_Tout, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                            .addComponent(Rent_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(90, 90, 90)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Rent_LItemName)
                                            .addComponent(Rent_LItemDesc)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(Rent_LFee)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Rent_LFee1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Rent_Fee, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Rent_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(24, 24, 24)))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rent_LDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Rent_LStuNo)
                                    .addComponent(Rent_LStuName)
                                    .addComponent(Rent_LSection))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Rent_StuName)
                                    .addComponent(Rent_StuNo)
                                    .addComponent(Rent_Sect, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(RentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Rent_Ldate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Rent_CurrDate)
                            .addComponent(Officer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RentLabel)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rent_Ldate)
                            .addComponent(Rent_CurrDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Officer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rent_LStuNo)
                    .addComponent(Rent_StuNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rent_LStuName)
                    .addComponent(Rent_StuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rent_LSection)
                    .addComponent(Rent_Sect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Rent_LItemName)
                            .addComponent(Rent_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rent_LItemDesc)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rent_Fee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rent_LFee)
                            .addComponent(Rent_LFee1))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rent_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rent_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Rent_LDetails)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rent_LDTR, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Rent_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Rent_Room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rent_LRoom))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rent_LTin)
                            .addComponent(Rent_Tin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Rent_LTout)
                            .addComponent(Rent_Tout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(124, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void inv_directMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inv_directMouseClicked
        String logname = Logged_Name.getText();
        IRIS_Inventory inv = new IRIS_Inventory(logname);
        inv.setVisible(true);
        inv.pack();
        inv.setLocationRelativeTo(null);
        inv.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_inv_directMouseClicked

    private void inv_directActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inv_directActionPerformed

    }//GEN-LAST:event_inv_directActionPerformed

    private void out_directMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_out_directMouseClicked
        
        IRIS_LogIn out = new IRIS_LogIn();
        out.setVisible(true);
        out.pack();
        out.setLocationRelativeTo(null);
        out.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_out_directMouseClicked

    private void out_directActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_out_directActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_out_directActionPerformed

    private void rs_directActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs_directActionPerformed
        String logname = Logged_Name.getText();
        //IRIS_RentalSchedule rs = new IRIS_RentalSchedule(logname);
        //rs.setVisible(true);
        //rs.pack();
        //rs.setLocationRelativeTo(null);
        //rs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_rs_directActionPerformed

    private void tr_directMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tr_directMouseClicked
        
    }//GEN-LAST:event_tr_directMouseClicked

    private void rf_directMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rf_directMouseClicked
        String logname = Logged_Name.getText();
        IRIS_RentalForm rf = new IRIS_RentalForm(logname);
        rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(null);
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_rf_directMouseClicked

    private void rf_directActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rf_directActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rf_directActionPerformed

    private void Rent_CurrDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rent_CurrDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rent_CurrDateActionPerformed

    private void Rent_StuNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rent_StuNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rent_StuNoActionPerformed

    private void Rent_StuNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rent_StuNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rent_StuNameActionPerformed

    private void Rent_RoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rent_RoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rent_RoomActionPerformed

    private void Rent_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rent_NameActionPerformed
        Available f = new Available();
        ResultSet rs = null;
        String rname = Rent_Name.getSelectedItem().toString();

        rs = f.find(Rent_Name.getSelectedItem().toString());
        try{
            if(rs.next()){
                itemid = rs.getInt("item_id");
                Rent_ItemDesc.setText(rs.getString("item_description"));
                if(rname.equals("TV"))
                Rent_Fee.setText("50");
                else
                Rent_Fee.setText("0");
            }  else{
                JOptionPane.showMessageDialog(null, "Item Not Available");
                Rent_ItemDesc.setText(null);
                Rent_Fee.setText(null);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_Rent_NameActionPerformed

    private void Rent_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rent_ConfirmActionPerformed
        try {
            String stuno = Rent_StuNo.getText();
            String stuname = Rent_StuName.getText();
            String stusect = Rent_Sect.getText();

            Date drent = Rent_DateChooser.getDate();
            String drent2 = dateformat.format(drent);
            java.util.Date dateStr2 = dateformat.parse(drent2);
            java.sql.Date dateDB2 = new java.sql.Date(dateStr2.getTime());
            
            String room = Rent_Room.getText();
            String timein = (String) Rent_Tin.getValue();
            String timeout = (String) Rent_Tout.getValue();

            String itemname = Rent_Name.getSelectedItem().toString();
            String itemdesc = Rent_ItemDesc.getText();
            String fee = Rent_Fee.getText();

            String officer = Officer_Name.getText();
            java.util.Date dateStr = dateformat.parse(rdate);
            java.sql.Date dateDB = new java.sql.Date(dateStr.getTime());

            if(drent2.equals(rdate))
            {
                Rent_DateChooser.setCalendar(null);
                
                String[] options1 = {"Yes", "No"};
                    int x;
                    x = JOptionPane.showOptionDialog(null, "Cannot Reserve on Same Date!\n Rent Instead?", "Confirmation",JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,null, options1, options1[0]);
                    if(options1[0].equals(x))
                    {String logname = Officer_Name.getText();
                        IRIS_RentalForm res = new IRIS_RentalForm(logname);
                        res.setVisible(true);
                        res.pack();
                        res.setLocationRelativeTo(null);
                        res.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();}
                    else
                        JOptionPane.showMessageDialog(null, "Please change the Date to Rent");

            }
            else{
            PreparedStatement ps,upd;
            String query = "INSERT INTO `rental`( `rn_stuno`, `rn_stuname`, `rn_section`, `rn_dtr`, `rn_room`, `rn_tmin`, `rn_tmout`, `rn_itemid`, `rn_itemname`, `rn_itemdesc`, `rn_fee`, `rn_oic`, `rn_cdate`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
            String ud = "UPDATE inventory i INNER JOIN rental r ON i.item_id = r.rn_itemid SET i.item_availability = 'Under Rent' WHERE i.item_id = r.rn_itemid";
            
            try {
                ps = IRIS_Connection.getConnection().prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
                upd = IRIS_Connection.getConnection().prepareStatement(ud);
                
                ps.setString(1,stuno);
                ps.setString(2,stuname);
                ps.setString(3,stusect);
                ps.setDate(4,dateDB2);
                ps.setString(5,room);
                ps.setString(6,timein);
                ps.setString(7,timeout);
                ps.setInt(8,itemid);
                ps.setString(9,itemname);
                ps.setString(10,itemdesc);
                ps.setString(11,fee);
                ps.setString(12,officer);
                ps.setDate(13,dateDB);
                ps.executeUpdate();
                
                upd.executeUpdate();
                
                ResultSet ts = ps.getGeneratedKeys();
                int rec_id=0;
                if (ts.next()){
                    rec_id= ts.getInt(1);
                }
                if(rec_id > 0)
                {
                    String[] options = {"Yes", "No"};
                    int x;
                    x = JOptionPane.showOptionDialog(null, "Student Name: "+stuname+"\nRent ID:"+rec_id+" Add Another Item to Reserve?", "Confirmation",JOptionPane.DEFAULT_OPTION,
                        JOptionPane.INFORMATION_MESSAGE,null, options, options[0]);
                    if(options[0].equals(x))
                    {String logname = Officer_Name.getText();
                        IRIS_ReservationForm res = new IRIS_ReservationForm(logname);
                        res.setVisible(true);
                        res.pack();
                        res.setLocationRelativeTo(null);
                        res.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();}

                    else{
                        String logname = Officer_Name.getText();
                        //IRIS_RentalSchedule res = new IRIS_RentalSchedule(logname);
                        //res.setVisible(true);
                        //res.pack();
                        //res.setLocationRelativeTo(null);
                        //res.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();

                    }
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Failed");
                Logger.getLogger(IRIS_RentalForm.class.getName()).log(Level.SEVERE, null, ex);
            }}

        } catch (ParseException ex) {
            Logger.getLogger(IRIS_RentalForm.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_Rent_ConfirmActionPerformed

    private void Rent_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rent_ClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rent_ClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IRIS_RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IRIS_RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IRIS_RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IRIS_RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IRIS_RentalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logged_Name;
    private javax.swing.JTextField Officer_Name;
    private javax.swing.JLabel RentLabel;
    private javax.swing.JButton Rent_Clear;
    private javax.swing.JButton Rent_Confirm;
    private javax.swing.JTextField Rent_CurrDate;
    private com.toedter.calendar.JDateChooser Rent_DateChooser;
    private javax.swing.JTextField Rent_Fee;
    private javax.swing.JTextArea Rent_ItemDesc;
    private javax.swing.JLabel Rent_LDTR;
    private javax.swing.JLabel Rent_LDetails;
    private javax.swing.JLabel Rent_LFee;
    private javax.swing.JLabel Rent_LFee1;
    private javax.swing.JLabel Rent_LItemDesc;
    private javax.swing.JLabel Rent_LItemName;
    private javax.swing.JLabel Rent_LRoom;
    private javax.swing.JLabel Rent_LSection;
    private javax.swing.JLabel Rent_LStuName;
    private javax.swing.JLabel Rent_LStuNo;
    private javax.swing.JLabel Rent_LTin;
    private javax.swing.JLabel Rent_LTout;
    private javax.swing.JLabel Rent_Ldate;
    private javax.swing.JComboBox<String> Rent_Name;
    private javax.swing.JTextField Rent_Room;
    private javax.swing.JTextField Rent_Sect;
    private javax.swing.JTextField Rent_StuName;
    private javax.swing.JTextField Rent_StuNo;
    private javax.swing.JSpinner Rent_Tin;
    private javax.swing.JSpinner Rent_Tout;
    private javax.swing.JButton inv_direct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logged_as;
    private javax.swing.JButton out_direct;
    private javax.swing.JButton rf_direct;
    private javax.swing.JButton rs_direct;
    private javax.swing.JButton tr_direct;
    // End of variables declaration//GEN-END:variables

}
